INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Afghanistan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Albania',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Algeria',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'American Samoa',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Andorra',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Angola',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Anguilla',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Antarctica',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Antigua And Barbuda',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Argentina',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Armenia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Aruba',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Australia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Austria',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Azerbaijan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bahamas',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bahrain',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bangladesh',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Barbados',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Belarus',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Belgium',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Belize',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Benin',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bermuda',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bhutan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bolivia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bosnia And Herzegowina',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Botswana',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bouvet Island',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Brazil',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'British Indian Ocean Territory',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Brunei Darussalam',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Bulgaria',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Burkina Faso',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Burundi',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cambodia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cameroon',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Canada',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cape Verde',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cayman Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Central African Republic',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Chad',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Chile',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'China',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Christmas Island',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cocos (Keeling) Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Colombia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Comoros',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Congo',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cook Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Costa Rica',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cote D><Ivoire',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Croatia (Local Name: Hrvatska)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cuba',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Cyprus',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Czech Republic',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Denmark',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Djibouti',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Dominica',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Dominican Republic',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'East Timor',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Ecuador',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Egypt',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'El Salvador',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Equatorial Guinea',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Eritrea',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Estonia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Ethiopia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Falkland Islands (Malvinas)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Faroe Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Fiji',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Finland',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'France',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'French Guiana',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'French Polynesia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'French Southern Territories',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Gabon',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Gambia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Georgia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Germany',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Ghana',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Gibraltar',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Greece',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Greenland',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Grenada',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Guadeloupe',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Guam',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Guatemala',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Guinea',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Guinea-Bissau',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Guyana',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Haiti',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Heard And Mc Donald Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Holy See (Vatican City State)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Honduras',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Hong Kong',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Hungary',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Icel And',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'India',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Indonesia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Iran (Islamic Republic Of)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Iraq',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Ireland',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Israel',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Italy',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Jamaica',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Japan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Jordan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Kazakhstan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Kenya',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Kiribati',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Korea, Dem People><S Republic',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Korea, Republic Of',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Kuwait',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Kyrgyzstan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Lao People><S Dem Republic',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Latvia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Lebanon',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Lesotho',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Liberia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Libyan Arab Jamahiriya',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Liechtenstein',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Lithuania',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Luxembourg',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Macau',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Macedonia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Madagascar',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Malawi',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Malaysia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Maldives',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mali',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Malta',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Marshall Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Martinique',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mauritania',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mauritius',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mayotte',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mexico',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Micronesia, Federated States',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Moldova, Republic Of',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Monaco',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mongolia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Montserrat',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Morocco',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Mozambique',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Myanmar',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Namibia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Nauru',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Nepal',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Netherlands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Netherlands Ant Illes',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'New Caledonia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'New Zealand',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Nicaragua',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Niger',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Nigeria',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Niue',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Norfolk Island',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Northern Mariana Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Norway',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Oman',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Pakistan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Palau',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Panama',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Papua New Guinea',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Paraguay',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Peru',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Philippines',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Pitcairn',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Poland',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Portugal',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Puerto Rico',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Qatar',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Reunion',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Romania',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Russian Federation',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Rwanda',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Saint K Itts And Nevis',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Saint Lucia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Saint Vincent, The Grenadines',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Samoa',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'San Marino',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Sao Tome And Principe',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Saudi Arabia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Senegal',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Seychelles',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Sierra Leone',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Singapore',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Slovakia (Slovak Republic)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Slovenia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Solomon Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Somalia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'South Africa',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'South Georgia , S Sandwich Is.',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Spain',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Sri Lanka',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'St. Helena',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'St. Pierre And Miquelon',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Sudan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Suriname',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Svalbard, Jan Mayen Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Sw Aziland',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Sweden',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Switzerland',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Syrian Arab Republic',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Taiwan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Tajikistan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Tanzania, United Republic Of',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Thailand',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Togo',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Tokelau',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Tonga',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Trinidad And Tobago',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Tunisia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Turkey',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Turkmenistan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Turks And Caicos Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Tuvalu',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Uganda',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Ukraine',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'United Arab Emirates',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'United Kingdom',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'United States',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'United States Minor Is.',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Uruguay',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Uzbekistan',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Vanuatu',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Venezuela',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Viet Nam',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Virgin Islands (British)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Virgin Islands (U.S.)',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Wallis And Futuna Islands',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Western Sahara',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Yemen',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Yugoslavia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Zaire',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Zambia',default,default,default);
INSERT INTO `pr_areas` (ID,name,parent_id,type,child_type) values (NULL,'Zimbabwe',default,default,default);
UPDATE `pr_areas` SET parent_id = 0, type = 1;