INSERT INTO pr_prop_types values(NULL,'Terraced');
INSERT INTO pr_prop_types values(NULL,'End Terraced');
INSERT INTO pr_prop_types values(NULL,'Semi-Detached');
INSERT INTO pr_prop_types values(NULL,'Detached');
INSERT INTO pr_prop_types values(NULL,'Cluster House');
INSERT INTO pr_prop_types values(NULL,'Ground Flat');
INSERT INTO pr_prop_types values(NULL,'Studio');
INSERT INTO pr_prop_types values(NULL,'Ground Maisonette');
INSERT INTO pr_prop_types values(NULL,'Maisonette');
INSERT INTO pr_prop_types values(NULL,'Bungalow');
INSERT INTO pr_prop_types values(NULL,'Terraced Bungalow');
INSERT INTO pr_prop_types values(NULL,'Semi-Detached Bungalow');
INSERT INTO pr_prop_types values(NULL,'Detached Bungalow');
INSERT INTO pr_prop_types values(NULL,'Mobile Home');
INSERT INTO pr_prop_types values(NULL,'Hotel');
INSERT INTO pr_prop_types values(NULL,'Guest House');
INSERT INTO pr_prop_types values(NULL,'Commercial Property');
INSERT INTO pr_prop_types values(NULL,'Land');
INSERT INTO pr_prop_types values(NULL,'Link Detached House');
INSERT INTO pr_prop_types values(NULL,'Town House');
INSERT INTO pr_prop_types values(NULL,'Cottage');
INSERT INTO pr_prop_types values(NULL,'Chalet');
INSERT INTO pr_prop_types values(NULL,'Unique');
INSERT INTO pr_prop_types values(NULL,'House');
INSERT INTO pr_prop_types values(NULL,'Villa');
INSERT INTO pr_prop_types values(NULL,'Apartment');
INSERT INTO pr_prop_types values(NULL,'Penthouse');
INSERT INTO pr_prop_types values(NULL,'Finca');
INSERT INTO pr_prop_types values(NULL,'Barn Conversion');
INSERT INTO pr_prop_types values(NULL,'Serviced Apartments');
INSERT INTO pr_prop_types values(NULL,'Parking');
INSERT INTO pr_prop_types values(NULL,'Sheltered Housing');
INSERT INTO pr_prop_types values(NULL,'Retirement Property');
INSERT INTO pr_prop_types values(NULL,'House Share');
INSERT INTO pr_prop_types values(NULL,'Flat Share');
INSERT INTO pr_prop_types values(NULL,'Park Home');
INSERT INTO pr_prop_types values(NULL,'Garages');
INSERT INTO pr_prop_types values(NULL,'Farm House');
INSERT INTO pr_prop_types values(NULL,'Equestrian');
INSERT INTO pr_prop_types values(NULL,'Duplex');
INSERT INTO pr_prop_types values(NULL,'Triplex');
INSERT INTO pr_prop_types values(NULL,'Longere');
INSERT INTO pr_prop_types values(NULL,'Gite');
INSERT INTO pr_prop_types values(NULL,'Barn');
INSERT INTO pr_prop_types values(NULL,'Trull');
INSERT INTO pr_prop_types values(NULL,'Mill');
INSERT INTO pr_prop_types values(NULL,'Ruins');
INSERT INTO pr_prop_types values(NULL,'Restaurant');
INSERT INTO pr_prop_types values(NULL,'Cafe');
INSERT INTO pr_prop_types values(NULL,'Mill');
INSERT INTO pr_prop_types values(NULL,'Trulli');
INSERT INTO pr_prop_types values(NULL,'Castle');
INSERT INTO pr_prop_types values(NULL,'Village House');
INSERT INTO pr_prop_types values(NULL,'Plot');
INSERT INTO pr_prop_types values(NULL,'Country House');
INSERT INTO pr_prop_types values(NULL,'Bar');
INSERT INTO pr_prop_types values(NULL,'Detached Villa');
INSERT INTO pr_prop_types values(NULL,'Semi-detached Villa');
INSERT INTO pr_prop_types values(NULL,'Bar');
INSERT INTO pr_prop_types values(NULL,'Shop');
INSERT INTO pr_prop_types values(NULL,'House Boat');
INSERT INTO pr_prop_types values(NULL,'Hotel Room');
INSERT INTO pr_prop_types values(NULL,'Flat');
